stages:
  - lint
  - build

test:
  stage: lint
  image: golang:latest
  before_script:
    - go mod download
  script:
    - go test -v -cover ./...

golangci-linter:
  stage: lint
  image:
    name: golangci/golangci-lint:latest
    entrypoint: [""]
  before_script:
    - go mod download
  script:
    - golangci-lint run --timeout 1h ./...

build:
  stage: build
  image: golang:latest
  before_script:
    - go mod download
  script:
    - find cmd -type d -mindepth 1 -maxdepth 1 -exec go build ./{}/... \;
  artifacts:
    untracked: true

build-docker:
  stage: build
  tags:
    - docker
  image: docker:stable
  services:
    - docker:dind
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA:latest .
    - docker push $CI_REGISTRY_IMAGE:latest